DROP TABLE IF EXISTS evidence;
DROP TABLE IF EXISTS body_sign;
DROP TABLE IF EXISTS eyes;
DROP TABLE IF EXISTS body;
DROP TABLE IF EXISTS dialog_participants;
DROP TABLE IF EXISTS dialog;
DROP TABLE IF EXISTS human;